### ISSUE TITLE
Minor improvement request: IRSA support is not highlighted for AWS resources 

### ISSUE THREAD

**Issue by vponoikoait** [kyverno/policy-reporter-docs#11]
As IRSA support is actually added to software, it may be useful to have a small highlight for related AWS resources, because on base it could've be assumed that usage of API keys would be required - https://github.com/kyverno/policy-reporter-docs/blob/main/content/02.%20core/targets.md?plain=1#L447

**Comment by fjogeleit** [comment]
thanks for your request, you're right. The docs were not updated after implementing the IRSA support. I'll take a look on it.

**Comment by fjogeleit** [comment]
I added a notice to AWS related targets about the IRSA support:

https://kyverno.github.io/policy-reporter/core/targets#kinesis-compatible-services
